//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDev2017.Week4.SimpleDataBinding
{


    public partial class c_SingleValueDataBinding
    {
    }
}
